---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/h287930/public_html
    - echo "Starting deployment..."
    - echo "Copying files to the deployment directory..."
    - /bin/rsync -av --exclude='.git' . $DEPLOY_PATH
    - echo "Deployment complete!"
